name: Build from Github, Deploy to Linux

on:
  push:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copying files to server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.REMOTE_PORT }}
          rm: true
          source: "/home/runner/work/TacoCat/TacoCat"
          target: "${{ secrets.REMOTE_DIR }}"
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cp -r /var/www/tacocat/github/workspace/* /var/www/tacocat
            rm -r /var/www/tacocat/github


# name: Build from Github, Deploy to AWS EC2

# on:
#   push:
#     branches: [ main ]

# jobs:
#  continuous-deployment:
#     runs-on: ubuntu-latest
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_DEFAULT_REGION: us-west-1

#     if: github.ref == 'refs/heads/main'
#     steps:
#   # Step 1
#       - name: Create CodeDeploy Deployment
#         run: 
#          aws deploy create-deployment
#             --application-name TacoCat
#             --deployment-group-name TacoCat
#             --deployment-config-name CodeDeployDefault.OneAtATime
#             --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
  
  
