name: Deploy to Linux Server

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-test-publish:
    uses: FullStackIndie/Reusable-Workflows/.github/workflows/deploy_static_website.yml@main
    with:
      folder_path: /var/www/html/js_challenges
      owner_name: FullStackIndie
      repo_name: TacoCat
    secrets: 
      SERVER_SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      SERVER_SSH_USERNAME: ${{ secrets.SERVER_SSH_USERNAME }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}